### PR TITLE
Adding exponenctial backoff to all errors of request not only http 5xx

### PR DESCRIPTION
**Pull request by mtrunkat**

### CODE REVIEW

**Comment by jancurn** [comment]
Tests are still failing...

**Comment by mtrunkat** [comment]
I know but when i opened travis there was no error in the log :)

st 6. 12. 2017 v 18:36 odesílatel Jan Čurn <notifications@github.com>
napsal:

**Comment by mtrunkat** [comment]
https://github.com/mochajs/mocha/issues/3044 for tomorrow, mocha test succeeds but doesn't exit - bug or feature of new mocha v4

**Comment by jancurn** [comment]
Yeah, I found this new feature of mocha the hard way in proxy-chain NPM :)

**Pull request merged**
